server:
  port: 0
spring:
  application:
    name: event-notifier-demo-client-b
  cloud:
    stream:
      bindings:
        output:
          destination: alarmDataSum
        input:
          destination: foo
        input1:
          destination: out1
        input2:
          destination: out2
  profiles:
    include: client-a-api, stream-binder-websocket