server:
  port: 0
spring:
  application:
    name: event-notifier-demo-client-a
  cloud:
    stream:
      bindings:
        output1:
          destination: out1
        output2:
          destination: out2
  profiles:
    include: client-a-api, stream-binder-websocket